
export interface EmployeeRequestType {
    employeeId: string,
    name: string,
    designation: string,
    date: string,
    description: string,
    leave: number,
    requestStatus: string,
    isRequestApproved: boolean,
}

export const EmployeeRequestData:EmployeeRequestType[] = [
    {
      employeeId: "35467",
      name: "John Doe",
      designation: "DevOps Engineer",
      date: "2025-04-15T10:00:00.000Z",
      description: "I am attending a certification training and need 10 days of leave for the same.",
      leave: 10,
      requestStatus: "pending",
      isRequestApproved: false,
    },
    {
      employeeId: "65789",
      name: "Jane Smith",
      designation: "Marketing Executive",
      date: "2025-03-10T09:00:00.000Z",
      description: "I have a family wedding and would like to request 10 days off to travel and attend.",
      leave: 10,
      requestStatus: "pending",
      isRequestApproved: false,
    },
    {
      employeeId: "67345",
      name: "Emily Johnson",
      designation: "Product Designer",
      date: "2025-02-25T12:30:00.000Z",
      description: "Requesting 5 days of leave for a personal vacation with my family.",
      leave: 5,
      requestStatus: "pending",
      isRequestApproved: false,
    },
    {
      employeeId: "12724",
      name: "Michael Brown",
      designation: "Sales Manager",
      date: "2025-01-15T08:45:00.000Z",
      description: "I will be undergoing a minor medical procedure and require 10 days to rest and recover.",
      leave: 10,
      requestStatus: "pending",
      isRequestApproved: false,
    },
    {
      employeeId: "83451",
      name: "David Williams",
      designation: "QA Tester",
      date: "2025-04-02T15:20:00.000Z",
      description: "I’m planning to visit my hometown and would like to apply for 5 days of leave.",
      leave: 5,
      requestStatus: "pending",
      isRequestApproved: false,
    },
    {
      employeeId: "37845",
      name: "Sophia Taylor",
      designation: "UI/UX Designer",
      date: "2025-03-28T11:15:00.000Z",
      description: "I have a design workshop in another city and need 11 days off for travel and participation.",
      leave: 11,
      requestStatus: "pending",
      isRequestApproved: false,
    },
    {
      employeeId: "92378",
      name: "Liam Harris",
      designation: "Frontend Developer",
      date: "2025-02-12T14:00:00.000Z",
      description: "Applying for 17 days leave to attend an international tech conference and sightseeing.",
      leave: 17,
      requestStatus: "pending",
      isRequestApproved: false,
    },
    {
      employeeId: "17634",
      name: "Isabella Moore",
      designation: "Visual Designer",
      date: "2025-04-05T09:30:00.000Z",
      description: "I will be attending a design bootcamp and request 12 days off for the event.",
      leave: 12,
      requestStatus: "pending",
      isRequestApproved: false,
    },
    {
      employeeId: "94576",
      name: "Ethan White",
      designation: "Automation QA Engineer",
      date: "2025-03-05T10:45:00.000Z",
      description: "I need 7 days off to assist my family during an important household event.",
      leave: 7,
      requestStatus: "pending",
      isRequestApproved: false,
    }
  ]
  